# Generated by Django 3.2.8 on 2021-10-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20211012_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_cover_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_more_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='More Image'),
        ),
    ]
