# Generated by Django 3.2.8 on 2021-10-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20211012_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_special',
            name='user_follower',
            field=models.ManyToManyField(related_name='_events_user_special_user_follower_+', to='events.User_special'),
        ),
        migrations.AddField(
            model_name='user_special',
            name='user_following',
            field=models.ManyToManyField(related_name='_events_user_special_user_following_+', to='events.User_special'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participant',
            field=models.ManyToManyField(blank=True, related_name='Event', to='events.User_special'),
        ),
        migrations.AlterField(
            model_name='user_special',
            name='user_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='user_special',
            name='user_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user_special',
            name='user_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
    ]
