# Generated by Django 3.2.8 on 2021-10-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20211030_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='Favorited_by', to='events.User_special'),
        ),
        migrations.AddField(
            model_name='user_special',
            name='user_blacklist',
            field=models.ManyToManyField(related_name='_events_user_special_user_blacklist_+', to='events.User_special'),
        ),
    ]
