# Generated by Django 3.2.8 on 2021-11-02 20:22

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20211030_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_more_image',
        ),
        migrations.AddField(
            model_name='event',
            name='event_capacity',
            field=models.CharField(default=0, max_length=20, verbose_name='Capacity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_cover_image',
            field=models.ImageField(blank=True, upload_to=events.models.upload_to, verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='user_special',
            name='user_avatar',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.upload_to, verbose_name='Avatar'),
        ),
    ]
