# Generated by Django 3.2.8 on 2021-11-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20211102_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_cover_image',
        ),
    ]
